% Script to do vibration / heatflow computation for UTC final report 
% example. 

[M,model]=InitializeVibroSimScript();

AddParamToParamdb(M,'cracksemimajoraxislen',3e-3,'m');
AddParamToParamdb(M,'cracksemiminoraxislen',1.5e-3,'m');


AddParamToParamdb(M,'simulationfreqstart',27600,'Hz');
AddParamToParamdb(M,'simulationfreqstep',10,'Hz');
AddParamToParamdb(M,'simulationfreqend',27800,'Hz');
AddParamToParamdb(M,'simulationburstfreq',27710,'Hz');
AddParamToParamdb(M,'simulationneigs',40);  % Number of frequencies for modal analysis to seek out
AddParamToParamdb(M,'simulationeigsaround',10000,'Hz'); % Center frequency for modal analysis

AddParamToParamdb(M,'simulationtimestart',0.2,'s');
AddParamToParamdb(M,'simulationtimestep',0.02,'s');
AddParamToParamdb(M,'simulationtimeend',1.8,'s');

AddParamToParamdb(M,'simulationcameranetd',.022,'K');
AddParamToParamdb(M,'simulationsurfaceemissivity',1.0);
ObtainDCParameter(M,'simulationsurfaceemissivity');

% Laser (displacement or velocity detection) coordinates
AddParamToParamdb(M,'laserx',.07,'m');
AddParamToParamdb(M,'lasery',.0254/4.0,'m');
AddParamToParamdb(M,'laserz',0.0,'m');

% Laser (displacement or velocity detection) direction vector
AddParamToParamdb(M,'laserdx',0);
AddParamToParamdb(M,'laserdy',0);
AddParamToParamdb(M,'laserdz',1);

% Crack position
AddParamToParamdb(M,'simulationcrackx',.07,'m');
AddParamToParamdb(M,'simulationcracky',.0254/2.0,'m');
AddParamToParamdb(M,'simulationcrackz',0,'m');



AddParamToParamdb(M,'amplitude',2.32,'V');
AddParamToParamdb(M,'xducercalib',fullfile(fileparts(which('BuildVibroModel')),'support','xducercalibration_19PM1620G.dat'));
AddParamToParamdb(M,'spclength',.1558,'m');
AddParamToParamdb(M,'spcwidth',.0254,'m');
AddParamToParamdb(M,'spcthickness',.012,'m');

% These parameters are book values for Ti-6-4 material 
AddParamToParamdb(M,'spcmaterial','Ti-6-4');
AddParamToParamdb(M,'spcYoungsModulus',113.8e9,'Pa');
AddParamToParamdb(M,'spcDensity',4430,'kg/m^3');
AddParamToParamdb(M,'spcPoissonsRatio',0.34,''); % book value
AddParamToParamdb(M,'spcEta',5e-5,'');
AddParamToParamdb(M,'spcThermalConductivity',6.7,'W/m/K');
AddParamToParamdb(M,'spcSpecificHeatCapacity',526.3,'J/kg/K');

AddParamToParamdb(M,'spcmeshtype','TETRAHEDRAL');
%AddParamToParamdb(M,'spcmeshtype','HEXAHEDRAL');
AddParamToParamdb(M,'spcmeshsize',.004,'m');
%AddParamToParamdb(M,'spcfacemethod','FreeQuad');
%AddParamToParamdb(M,'spcsweepelements',15)

AddParamToParamdb(M,'tlmountoffsetx',.13,'m');
AddParamToParamdb(M,'blmountoffsetx',.12,'m');
AddParamToParamdb(M,'brmountoffsetx',.02,'m');
AddParamToParamdb(M,'trmountoffsetx',.01,'m');
AddParamToParamdb(M,'xduceroffsetx',.07,'m');



AddParamToParamdb(M,'isolatorthickness',.00125,'m');
AddParamToParamdb(M,'isolatorlength',.010,'m');
AddParamToParamdb(M,'isolatorwidth',.0254,'m');
AddParamToParamdb(M,'isolatormeshtype','HEXAHEDRAL');
AddParamToParamdb(M,'isolatorfacemethod','FreeQuad');
AddParamToParamdb(M,'isolatormeshsize',.004,'m');
AddParamToParamdb(M,'isolatorsweepelements',6,'');
AddParamToParamdb(M,'isolatorThermalConductivity',.05,'W/m/K');  % this number may not be very meaningful
AddParamToParamdb(M,'isolatorSpecificHeatCapacity',2500,'J/kg/K');  % this number may not be very meaningful

AddParamToParamdb(M,'isolatormaterial','isocardstock');
AddParamToParamdb(M,'isolatorYoungsModulus',3.5e6,'Pa');
AddParamToParamdb(M,'isolatorDensity',870,'kg/m^3');
AddParamToParamdb(M,'isolatorPoissonsRatio',0.3,'');
AddParamToParamdb(M,'isolatorEta',.5,'');

AddParamToParamdb(M,'couplantthickness',.00025,'m');
AddParamToParamdb(M,'couplantlength',.010,'m');
AddParamToParamdb(M,'couplantwidth',.010,'m');
AddParamToParamdb(M,'couplantmeshtype','HEXAHEDRAL');
AddParamToParamdb(M,'couplantfacemethod','FreeQuad');
AddParamToParamdb(M,'couplantmeshsize',.004,'m');
AddParamToParamdb(M,'couplantsweepelements',4,'');

AddParamToParamdb(M,'couplantmaterial','coupcardstock');
AddParamToParamdb(M,'couplantYoungsModulus',3.5e6,'Pa');
AddParamToParamdb(M,'couplantDensity',870,'kg/m^3');
AddParamToParamdb(M,'couplantPoissonsRatio',0.3,'');
AddParamToParamdb(M,'couplantEta',.5,'');
AddParamToParamdb(M,'couplantThermalConductivity',.05,'W/m/K');  % this number may not be very meaningful
AddParamToParamdb(M,'couplantSpecificHeatCapacity',2500,'J/kg/K');  % this number may not be very meaningful


AddParamToParamdb(M,'meshsizemin',.001,'m');
AddParamToParamdb(M,'meshsize',.004,'m');

AddParamToParamdb(M,'excitation_t0',0.2,'s');
AddParamToParamdb(M,'excitation_t1',0.21,'s');
AddParamToParamdb(M,'excitation_t2',1.199,'s');
AddParamToParamdb(M,'excitation_t3',1.2,'s');

% Load in xducercalib file to xducercalib function, set up xducerdisplacement as variable (WARNING: This step can be slow!)
CreateTransducerDisplacementVariable(M);

CreateExcitationWindow(M,'excitationwindow', ...
		       ObtainDCParameter(M,'excitation_t0','s'), ...
		       ObtainDCParameter(M,'excitation_t1','s'), ...
		       ObtainDCParameter(M,'excitation_t2','s'), ...
		       ObtainDCParameter(M,'excitation_t3','s'));

CreateCameraNoise(M,'cameranoise',ObtainDCParameter(M,'simulationcameranetd','K'));




couplant_coord=[ .14/2,   .0254/2,     .012,      NaN    ];
isolator_coords=[.13,     .0254/2,     0,   0.0,  % top-left
		 .01,     .0254/2,     0,   0.0,  % top-right
                 .12,     .0254/2,     .012,      0.0,  % bottom-left
		 .02,     .0254/2,     .012,      0.0]; % bottom-right

% ( NaN for angle causes it to create a circular isolator)

BuildVibroModelNoInit(M,'run',...
			[], ...
			@(M,geom,tag) ...
			AttachThinCouplantIsolators(M,geom,tag, @(M,geom,tag) ...
						    CreateRectangularBarSpecimen(M,geom,tag), ...
						    couplant_coord, ...
						    isolator_coords), ...
			@(M,geom,specimen) CreateCrack(M,geom,'crack',specimen, ...
						       { ObtainDCParameter(M,'simulationcrackx','m'), ...
							 ObtainDCParameter(M,'simulationcracky','m'), ...
							 ObtainDCParameter(M,'simulationcrackz','m') }, ...
						       ObtainDCParameter(M,'cracksemimajoraxislen'), ...
						       ObtainDCParameter(M,'cracksemiminoraxislen'), ...
						       [0,1,0], ...
						       [0,0,-1], ...
						       [ .0005, -8 ; .0010, 6 ; .0015, 30; .0020, 80], ...
						       {'solidmech_harmonicsweep','solidmech_harmonicburst'},...
						       [],{'2727','2775','1262','158'}), ... % Crack heating powers from Bill Meeker calculation
			    @(M,geom,specimen,flaw) VibroPhysics(M,geom,specimen,flaw,'process'),...
			@(model) Seq(VibroResults(model), ...
				     @(model) model.result('vibro_heating_plot').feature('vibro_heating_plot_surface').create('def1', 'Deform'), ...
				     @(model) model.result('vibro_heating_plot').run, ...
				     @(model) model.result('vibro_heating_plot').feature('vibro_heating_plot_surface').set('rangecolormax', '.25'), ...
				     @(model) model.view('specimen_view').camera.set('zoomanglefull', 6), ...
				     @(model) model.result.export.create('img1', 'Image3D'), ...
				     @(model) model.result.export('img1').set('unit', 'px'), ...
				     @(model) model.result.export('img1').set('height', '600'), ...
				     @(model) model.result.export('img1').set('width', '800'), ...
				     @(model) model.result.export('img1').set('lockratio', 'off'), ...
				     @(model) model.result.export('img1').set('resolution', '96'), ...
				     @(model) model.result.export('img1').set('size', 'manual'), ...
				     @(model) model.result.export('img1').set('antialias', 'on'), ...
				     @(model) model.result.export('img1').set('title', 'on'), ...
				     @(model) model.result.export('img1').set('legend', 'on'), ...
				     @(model) model.result.export('img1').set('logo', 'on'), ...
				     @(model) model.result.export('img1').set('options', 'off'), ...
				     @(model) model.result.export('img1').set('fontsize', '9'), ...
				     @(model) model.result.export('img1').set('customcolor', [1 1 1]), ...
				     @(model) model.result.export('img1').set('background', 'color'), ...
				     @(model) model.result.export('img1').set('qualitylevel', '92'), ...
				     @(model) model.result.export('img1').set('qualityactive', 'off'), ...
				     @(model) model.result.export('img1').set('imagetype', 'png'), ...
				     @(model) model.result.export('img1').set('axisorientation', 'on'), ...
				     @(model) model.result.export('img1').set('grid', 'on'), ...
				     @(model) model.result('vibro_modal_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_modal_plot').run, ...
				     @(model) model.result('vibro_modal_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_modal_plot').set('windowtitle', 'Graphics'), ...
				     @(model) model.result.export('img1').set('plotgroup', 'vibro_heating_plot'), ...
				     @(model) model.result('vibro_heating_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_heating_plot').run, ...
				     @(model) model.result('vibro_heating_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_heating_plot').set('windowtitle', 'Graphics'), ...
				     @(model) model.result.export('img1').set('width', '1600'), ...
				     @(model) model.result.export('img1').set('height', '1200'), ...
				     @(model) model.result.export('img1').set('resolution', '192'), ...
				     @(model) model.result.export('img1').set('options', 'on'), ...
				     @(model) model.result.export('img1').set('background', 'current'), ...
				     @(model) model.result('vibro_heating_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_heating_plot').run, ...
				     @(model) model.result('vibro_heating_plot').set('window', 'graphics'), ...
				     @(model) model.result('vibro_heating_plot').set('windowtitle', 'Graphics'), ...
				     @(model) model.result.export('img1').set('pngfilename', '/tmp/UTCFinalReportDemo.png'), ...
				     @(model) model.result.export('img1').set('fontsize', '19'), ...
				     @(model) model.result.export('img1').run), ...
		      fullfile('/','tmp',char(java.lang.System.getProperty('user.name')),sprintf('UTCFinalReport_script_%s.mph',char(java.lang.System.getProperty('user.name'))))), ...

% if you call BuildVibroModel and it errors out, you can
% still get access to M and model and everything under them with:
% M=FindWrappedObject([],'Model'), ...
% model=M.node, ...

% set color range max to 0.25

solidmech_modal_study=FindWrappedObject(M,'solidmech_modal_study');
%solidmech_modal_study.node.run()

solidmech_harmonicsweep_study=FindWrappedObject(M,'solidmech_harmonicsweep_study');
%solidmech_harmonicsweep_study.node.run()

%RunAllStudies(model);


