#! /bin/sh

DESKTOP="YES"
GRAPHICS="NO"   # "comsol server graphics" option
RUN=""
OPEN=""
while [[ $# > 0 ]]
do
  key="$1"

  case $key in
    "-nodesktop")
    # echo "nodesktop"
    DESKTOP="NO"
    ;;
    "graphics")
    GRAPHICS="YES"
    ;;
    "-open")   # just run regular COMSOL but open preexisting file
    OPEN="$2"
    shift
    ;;
    "-r") # run MATLAB command
    RUN="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
  esac
  shift
done




# Find directory this script is stored in
# From 
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  export VIBROSIMDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$VIBROSIMDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export VIBROSIMDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


# find MATLAB based on the copy in the path 
MATLABSOURCE=`which matlab`
while [ -h "$MATLABSOURCE" ]; do # resolve $MATLABSOURCE until the file is no longer a symlink
  export RUNMATLABDIR="$( cd -P "$( dirname "$MATLABSOURCE" )" && pwd )"
  MATLABSOURCE="$(readlink "$MATLABSOURCE")"
  [[ $MATLABSOURCE != /* ]] && MATLABSOURCE="$RUNMATLABDIR/$MATLABSOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
export RUNMATLABDIR="$( cd -P "$( dirname "$MATLABSOURCE" )" && pwd )"

# Now RUNMATLABDIR is the directory containing the "matlab" script. Let's go up to find the matlab root
# ... (identify it by the presence of "VersionInfo.xml")
while [ ! -f $RUNMATLABDIR/VersionInfo.xml ] && [ $RUNMATLABDIR != / ]; do 
  export RUNMATLABDIR="$( cd -P "$( dirname "$MATLABSOURCE" )" && cd .. && pwd )" 
done


if [ $RUNMATLABDIR == / ]; then 
   export RUNMATLABDIR=/usr/local/matlab   # Default to /usr/local/matlab (which should be a symlink to /usr/local/MATLAB/R20xxx) if we just can't find it
fi

export INTERNALMATLABDIR=$RUNMATLABDIR

#export RUNMATLABDIR=/usr/local/matlab   # The MATLAB we run
#export INTERNALMATLABDIR=/usr/local/MATLAB/R2015b  # The MATLAB we ask COMSOL to run...


export COMSOL_MATLAB_PATH=$VIBROSIMDIR:$VIBROSIMDIR/support
#export MATLABPATH=$VIBROSIMDIR:$VIBROSIMDIR/conf:$VIBROSIMDIR/definitions:$VIBROSIMDIR/geometry:$VIBROSIMDIR/material:$VIBROSIMDIR/mesh:$VIBROSIMDIR/physics:$VIBROSIMDIR/results:$VIBROSIMDIR/study:$VIBROSIMDIR/support:$VIBROSIMDIR/util
export MATLABPATH=$VIBROSIMDIR:$VIBROSIMDIR/m_files:$MATLABPATH

if [ -z "$OPEN" ]; then 
  # only run MATLAB process if we are not opening a .mph file
 
  # Run MATLAB with or without desktop as requested 
  if [ "$DESKTOP" = "NO" ]; then
    # echo "nodesktop!"
    if [ -n "$RUN" ]; then
      gnome-terminal -t 'COMSOL MATLAB' -x sh -c "$RUNMATLABDIR/bin/matlab -nodesktop -r $RUN" &
    else
      gnome-terminal -t 'COMSOL MATLAB' -x sh -c "$RUNMATLABDIR/bin/matlab -nodesktop -softwareopengl" &
    fi
  else
    # echo "desktop!"
    if [ -n "$RUN" ]; then
      $RUNMATLABDIR/bin/matlab -desktop -softwareopengl -r "$RUN" &
    else
      $RUNMATLABDIR/bin/matlab -desktop -softwareopengl &
    fi
  fi 

  if [ "$GRAPHICS" = "YES" ]; then 
    # "graphics" command (graphics engine built into server) implies no client
    comsol mphserver -mlroot "$INTERNALMATLABDIR" graphics
    
  else 
    # No graphics... start client in case user wants to connect
    comsol mphclient -mlroot "$INTERNALMATLABDIR" & 
    comsol mphserver -mlroot "$INTERNALMATLABDIR"  
  fi

else

  # With '-open' parameter run regular comsol with -open parameter 
  comsol -mlroot "$INTERNALMATLABDIR" -open "$OPEN"
fi
